# Generated by Django 2.2.7 on 2019-12-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('depart_name', models.CharField(max_length=200)),
                ('origin_pic', models.CharField(max_length=200)),
                ('snap_pic', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
