# Generated by Django 2.2.7 on 2019-12-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Awards'),
        ),
    ]
